name: selres

dependencies:
  - python >=3.8,<=3.9.7
  - tqdm
  - antlr4-python3-runtime=4.8
  - hydra-core=1.1.1
  - transformers
  - tokenizers
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - setuptools <=59.5.0
  - pytorch=1.11.0
  - cudatoolkit=11.3
  - pip
  - pip:
    - -r requirements.txt
